#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("freetelec.Droid.Resource", IsApplication=true)]

namespace freetelec.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int green = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int left = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int moins = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int next = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int play = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int plus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int prev = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rec = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int red = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int right = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int settings = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int un = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int up = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int yellow = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int Mono_Android_Theme_Splash = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
